version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - kafka_network
      
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1  # Set replication factor to 1
    ports:
      - "9092:9092"
    networks:
      - kafka_network

  kafka-producer:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - kafka
    tty: true # Keeps the container running
    entrypoint:
      - /bin/sh
      - -c
      - |
        echo "Producing messages to Kafka topic 'test-topic'"
        echo "Press CTRL+C to stop."
        sleep 50
        kafka-console-producer --broker-list kafka:9092 --topic test-topic

    networks:
      - kafka_network

  kafka-consumer:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - kafka
    entrypoint:
      - /bin/sh
      - -c
      - |
        echo "Consuming messages from Kafka topic 'test-topic'"
        sleep 50
        kafka-console-consumer --bootstrap-server kafka:9092 --topic test-topic --from-beginning

    networks:
      - kafka_network

networks:
  kafka_network:
    driver: bridge

